package com.osroyale.content.clanchannel.content;

/**
 * The clan task key set.
 *
 * @author Daniel
 */
public enum ClanTaskKey {
    /* Player Killing */
    PLAYER_KILLING,

    /* Monster Killing */
    SAND_CRAB,
    HILL_GIANT,
    ROCK_CRAB,
    BLACK_DEMON,
    BLUE_DRAGON,
    GREEN_DRAGON,
    RED_DRAGON,
    BLACK_DRAGON,
    GREATER_DEMON,
    GHOST,
    SKELETON,
    BLACK_KNIGHT,
    BABY_BLUE_DRAGON,
    BAT,
    CHAOS_DWARF,
    MAGIC_AXE,
    CAVE_CRAWLER,
    CRAWLING_HAND,
    BANSHEE,
    ICE_FIEND,
    HELLHOUND,
    CAVE_HORROR,
    STEEL_DRAGON,
    PYRE_FIEND,
    FIRE_GIANT,
    BASILISK,
    COCKATRICE,
    DUST_DEVIL,
    SPIRITUAL_RANGER,
    SPIRITUAL_WARRIOR,
    SPIRITUAL_MAGE,
    BLOODVELD,
    NECHRYAEL,
    SMOKE_DEVIL,
    DEMONIC_GORILLA,
    LIZARD_SHAMAN,

    KING_BLACK_DRAGON,
    SCORPIA,
    VETION,
    CHAOS_ELEMENTAL,
    CHAOS_FANATIC,
    CRAZY_ARCHAEOLOGIST,
    CALLISTO,
    VENNANTIS,
    SKELETAL_WYVERN,
    ABYSSAL_DEMON,
    GENERAL_GRAARDOR,
    COMMANDER_ZILYANA,
    KREEARRA,
    KRIL_TSUTSAROTH,


    /* Skilling */
    THIEVING_STALL,
    CHOP_WILLOW_LOG,
    BURN_WILLOW_LOG,
    SHARK,
    DARK_CRAB,
    YEW_LOG,
    MAGIC_LOG,
    RUNITE_ORES,
    SUPER_COMBAT_POTION,
    SUPER_RESTORE_POTION,
    MAGIC_SHORTBOW,
    YEW_SHORTBOW,
    DEATH_RUNE,
    BLOOD_RUNE,
    AGILITY_COURSE
}
